---
name: Terraform

on:
  pull_request:
  push:
    branch:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform-fmt:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: fmt
          tf_actions_comment: true

  terraform-validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: init
          tf_actions_comment: true
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        env:
          AWS_DEFAULT_REGION: eu-west-1
        with:
          tf_actions_version: latest
          tf_actions_subcommand: validate
          tf_actions_comment: true

  terraform-docs:
    if: github.repository_owner == 'schubergphilis' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Update module usage docs and push any changes back to PR branch
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_args: '--sort-inputs-by-required'
          tf_docs_git_commit_message: 'terraform-docs: Update module usage'
          tf_docs_git_push: 'true'
          tf_docs_output_file: README.md
          tf_docs_output_method: inject
          tf_docs_find_dir: .

  tfsec:
    if: github.event_name == 'pull_request'
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.0.2
